openapi: 3.0.0
info:
  version: 0.0.1
  title: Pagopa eCommerce payment methods handler
  description: This microservice handles payment methods.
  contact:
    name: pagoPA - Touchpoints team
tags:
  - name: payment-methods-handler
    description: Api's for handle payment methods
    externalDocs:
      url: https://pagopa.atlassian.net/wiki/spaces/I/pages/611516433/-servizio+payment+methods+service
      description: Technical specifications
externalDocs:
  url: https://pagopa.atlassian.net/wiki/spaces/I/pages/492339720/pagoPA+eCommerce+Design+Review
  description: Design review
servers:
  - url: https://api.platform.pagopa.it/payment-methods-handler
security:
  - ApiKeyAuth: []
paths:
  /payment-methods:
    get:
      tags:
        - payment-methods
      operationId: getAllPaymentMethods
      summary: Retrieve all Payment Methods (by filter)
      description: API for retrieve payment method using the request query parameter filters
      parameters:
        - name: amount
          in: query
          description: Payment Amount
          required: false
          schema:
            type: number
        - name: x-client-id
          in: header
          description: client id related to a given touchpoint
          required: true
          schema:
            type: string
            enum:
              - IO
              - CHECKOUT
      responses:
        '200':
          description: Payment method successfully retrieved
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentMethodsResponse'
        '500':
          description: Service unavailable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemJson'
components:
  schemas:
    PaymentMethodRequest:
      type: object
      description: New Payment method Request
      properties:
        clientId:
          type: string
          description: client id related to a given touchpoint
          enum:
            - IO
            - CHECKOUT
        name:
          type: string
          description: Payment method name
        description:
          type: string
          description: Payment method description string
        asset:
          type: string
          description: Asset name associated to this payment method
        status:
          $ref: "#/components/schemas/PaymentMethodStatus"
        paymentTypeCode:
          type: string
          description: Payment method type code
        ranges:
          description: Payment method ranges
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/Range"
        methodManagement:
          $ref: "#/components/schemas/PaymentMethodManagementType"
        brandAssets:
          description: Brand assets map associated to the method
          type: object
          additionalProperties:
            type: string

      required:
        - name
        - description
        - status
        - paymentTypeCode
        - ranges
        - clientId
        - methodManagement
    Range:
      type: object
      description: Payment amount range in eurocents
      properties:
        min:
          type: integer
          format: int64
          minimum: 0
          description: Range min amount
        max:
          type: integer
          format: int64
          minimum: 0
          description: Range max amount
    PaymentMethodResponse:
      type: object
      description: Payment method Response
      properties:
        id:
          type: string
          description: Payment method ID
        name:
          type: string
          description: Payment method name
        description:
          type: string
          description: Payment method description
        asset:
          type: string
          description: Payment method asset name
        status:
          $ref: "#/components/schemas/PaymentMethodStatus"
        methodManagement:
          $ref: "#/components/schemas/PaymentMethodManagementType"
        paymentTypeCode:
          type: string
          description: Payment method type code
        ranges:
          description: Payment amount range in eurocents
          type: array
          minItems: 1
          items:
            $ref: "#/components/schemas/Range"
        brandAssets:
          description: Brand assets map associated to the selected payment method
          type: object
          additionalProperties:
            type: string
      required:
        - id
        - name
        - description
        - status
        - paymentTypeCode
        - ranges
        - methodManagement
    PaymentMethodsResponse:
      type: object
      description: Payment methods response
      properties:
        paymentMethods:
          type: array
          items:
            $ref: '#/components/schemas/PaymentMethodResponse'
    ProblemJson:
      type: object
      description: Problem json structure
      properties:
        detail:
          description: Problem detail
          type: string
        status:
          description: Error status code
          maximum: 600
          minimum: 100
          type: integer
          format: int32
          example: 200
        title:
          description: Problem title
          type: string
    PaymentMethodStatus:
      type: string
      description: Payment method status
      enum:
        - ENABLED
        - DISABLED
        - INCOMING
    PaymentMethodManagementType:
      type: string
      description: |
        describes how to manage the payment method authorization flow in wallet and eCommerce domain
        REDIRECT if it must be managed with a redirect flow, 
        ONBOARDABLE if it must be managed with NPG and it is possible to save the payment method in the wallet, but also guest payment is accepted 
        NOT_ONBOARDABLE if it must be managed with NPG but the method cannot be saved, only guest payment is accepted
        ONBOARDABLE_ONLY if it must be managed with NPG and it is mandatory to save the payment method in the wallet to use it. Guest payment isn't accepted
        ONBORDABLE_WITH_PAYMENT if it must be managed with NPG and it is possible to save it, to use it as guest payment, and to onboard it during the payment
      enum:
        - REDIRECT
        - ONBOARDABLE
        - NOT_ONBOARDABLE
        - ONBOARDABLE_ONLY
        - ONBORDABLE_WITH_PAYMENT
  requestBodies:
    PaymentMethodRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/PaymentMethodRequest"
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: x-api-key