microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: "pagopa-ecommerce-payment-methods-handler"
  image:
    repository: pagopapcommonacr.azurecr.io/pagopaecommercepaymentmethodshandler
    tag: "1.0.1"
    pullPolicy: Always
  livenessProbe:
    handlerType: httpGet
    httpGet:
      path: /q/health/live
      port: 8080
    initialDelaySeconds: 2
    failureThreshold: 6
    periodSeconds: 3
  readinessProbe:
    handlerType: httpGet
    httpGet:
      path: /q/health/ready
      port: 8080
    initialDelaySeconds: 2
    failureThreshold: 6
    periodSeconds: 3
  deployment:
    create: true
    replicas: 3
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuprod.ecommerce.internal.platform.pagopa.it"
    path: /pagopa-ecommerce-payment-methods-handler/(.*)
    servicePort: 8080
  serviceAccount:
    name: "ecommerce-workload-identity"
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - all
  resources:
    requests:
      memory: "128Mi"
      cpu: "150m"
    limits:
      memory: "128Mi"
      cpu: "150m"
  autoscaling:
    enable: true
    minReplica: 3
    maxReplica: 10
    pollingInterval: 10 # seconds
    cooldownPeriod: 50 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
    advanced:
      horizontalPodAutoscalerConfig:
        behavior:
          scaleUp:
            stabilizationWindowSeconds: 60
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  envConfig:
    ROOT_LOG_LEVEL: INFO
    OTEL_RESOURCE_ATTRIBUTES: "service.name=pagopa-ecommerce-payment-methods-handler,deployment.environment=prod"
    OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-system.svc:4317"
    OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
    OTEL_LOGS_EXPORTER: none
    OTEL_TRACES_SAMPLER: "always_on"
    ECS_SERVICE_NAME: pagopa-ecommerce-payment-methods-handler
    ECS_SERVICE_ENVIRONMENT: prod
    SECURITY_API_KEY_SECURED_PATHS: "/payment-methods"
    AFM_URI_V1: "https://api.platform.pagopa.it/afm/calculator-service/v1"
    AFM_CONNECTION_TIMEOUT: "10000"
    AFM_READ_TIMEOUT: "10000"
  envSecret:
    SECURITY_API_KEY_PRIMARY: ecommerce-payment-methods-primary-api-key
    SECURITY_API_KEY_SECONDARY: ecommerce-payment-methods-secondary-api-key
    AFM_KEY: afm-api-key
  keyvault:
    name: "pagopa-p-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            labelSelector:
              matchLabels:
                app.kubernetes.io/instance: pagopaecommercepaymentmethodshandler
            namespaces: ["ecommerce"]
            topologyKey: topology.kubernetes.io/zone
  secretProviderClass:
    create: false
  azure:
    workloadIdentityClientId: "d5614882-90dd-47a1-aad1-cdf295201469"
